name: "Comprobación de presencia de ficheros básicos"
on: [pull_request, push]

jobs:
  file_presence:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Comprueba ficheros"
        uses: JJ/files-present-action@releases/v1
        with:
          files: "LICENSE, README.md, .gitignore, .travis.yml"
